name: Supabase Keep Alive (eduplatform)

on:
  schedule:
    # Her gün sabah 09:00'da (TSİ) otomatik çalışır
    - cron: '0 6 * * *'
  workflow_dispatch: # Manuel çalıştırma butonu

jobs:
  ping_supabase:
    runs-on: ubuntu-latest
    steps:
      - name: Send Request
        run: |
          curl -i -X GET "https://kscykywvwdilmfsflkkq.supabase.co/rest/v1/courses?select=id&limit=1" \
          -H "apikey: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtzY3lreXd2d2RpbG1mc2Zsa2txIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzM0ODA5MDQsImV4cCI6MjA4OTA1NjkwNH0.mWlLmb4ZTxZFptVxMQsKcc231mazNHpcd5TtY8vC2ew" \
          -H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtzY3lreXd2d2RpbG1mc2Zsa2txIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzM0ODA5MDQsImV4cCI6MjA4OTA1NjkwNH0.mWlLmb4ZTxZFptVxMQsKcc231mazNHpcd5TtY8vC2ew"
